---
apiVersion: v1
kind: Secret
metadata:
  name: toofics-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-vegas/toofics-backend-gitops
